---
- name: Compile the Neqo QCSD library and client
  hosts: wg_clients
  tasks:
    - name: Copy the experiment
      ansible.posix.synchronize:
        src: files/experiment-dir/
        dest: "{{ exp_path }}"
        copy_links: true
      when: copy_experiment | default(true)

    - name: Define the folder into which to clone the repo
      ansible.builtin.set_fact:
        third_party_dir: "{{ exp_path }}/third-party"

    - name: Ensure {{ third_party_dir }} directories exist
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ third_party_dir }}"
        - "{{ third_party_dir }}/bin"

    - name: Clone the neqo-qcsd repository
      ansible.builtin.git:
        repo: https://github.com/jpcsmith/neqo-qcsd.git
        dest: "{{ third_party_dir }}/neqo-qcsd"

    - name: Build and install the QCSD binaries
      ansible.builtin.command:
        chdir: "{{ third_party_dir }}"
        cmd: cargo install --path "neqo-qcsd/{{ item }}" --root "./" --locked
      loop:
        - neqo-client
        - neqo-client-mp

    - name: Find the shared libraries
      # Equivalent to `find third-party/neqo-qcsd/target/release/
      # \( -wholename '*/Release/lib/libnspr4.so'
      # -o -wholename '*/Release/lib/libnss3.so' \)
      # -exec cp {} third-party/lib/ \;`
      ansible.builtin.find:
        path: "{{ third_party_dir }}/neqo-qcsd/target/release/"
        pattern: "libnss3.so"
        recurse: true
      register: shared_libs

    - name: Link to the directory containing the shared library files
      ansible.builtin.file:
        src: "{{ shared_libs.files[0].path | dirname }}"
        dest: "{{ third_party_dir }}/lib"
        state: link
