---
n_gateways: 3
n_clients_per_gateway: 12

# Wireguard client and gateway keys.
#
# Client keys are indexed by region_id then client_id, whereas gateway
# keys are indexed by region_id
wg_keys:
  gateway:
    - private: "YIerCk0AzdSJMLi24cT1QKSX05yA5XiAAwluR/kLSkY="
      public: "Wo62rUO4iFGOro9RD5hsRTNf1ehsLVUoHDw3Oeqyiws="
    - private: "qIIYfM/3XGtyTyD3GZGno2eyfrBf2dBCvb6T5aIlSnU="
      public: "F77A0MVc9IqMSTAXRI14CfFhazmUEToemctoy5L4eyE="
    - private: "mAXavV61YIeExDKJqOFT69PyyTtdWudUwTkzA79kC0k="
      public: "0cWyfNQ67XTwCr/BdurhNXFty8kWCqWuWgWglirU9hM="
  client:
    - - private: "kKPjiNs3q39GRQ0AeqXRL7EqEwGdYLohdSfAXuhOD3o="
        public: "tgebJ6/VUz0kMHQKSfR8494Bw/B1wLkvMhWgTxRI8CA="
      - private: "CMrYgeXRmpxmWf2+prLYXtvOaen6Fo8Fkl2cD1R4G1I="
        public: "LOT3MIneb2SAMj6SSYRXuVK3qwlHXQbbw7dmSuT14GM="
      - private: "4CszentbL41EfShVc0WeaOGqHXukFyHV6Ycpq6KW8kA="
        public: "tNw9ihKDgTrlB04kp9j0cOGYNBTmpuHoPfh7yW/H33E="
      - private: "mMR3zASdErSXJPhZAT2JJ0TqmQX2R6Lf9fCf6bdeCXs="
        public: "0k3cjHRFMCrD2KgzB9XkRaPuENevY/egvDwYHVo6P1A="
      - private: "eI/6eccpn3FQi0ELQUYakGglY+Fgz4iLJj1NUPPFSW8="
        public: "O+q01VvoAHnRcWdtswCHdvRq5BbBhWTYXV70NoYtryg="
      - private: "yI9VOLfH7vNl75+T1VTvfAV8DKtfS8u9HzXtDNRjAUE="
        public: "6XT15QuxP4v1s1+unHvkAZyzuTpT2Wy0LYABleJub0U="
      - private: "6G8m3YtbPDfFxTzjCuPMAiHzFEDygtCvnS+zG5nOJE8="
        public: "fNQbeZzAd0UZX81BtPtxo7o3kcgZKwsURdmwAoBpry4="
      - private: "UMZzsA+P7DWOBS/s4S4SU+LhV4NxtIUSoNdJ8lrkKUs="
        public: "MbjiFV6u1nXk6CamqwSTZKzps/U6O6Ic6rZe97UfGz4="
      - private: "0LZb0W0/a/xfqdxmsokMVsquvf84pZE+MYEMs9r+d0w="
        public: "tAePzwEzX/XJpoLvdD0G/OaOj2542SGURiNuuDMtzEM="
      - private: "CFcFEdomJu/TnEe60sosHA+zvMwqt3WFdB/KhsUlJ1M="
        public: "PUQ08SMNRU6HAnQFMoyn4AU6zrWAiKBxlg0SEXUhemc="
      - private: "WGhVn5D8Pi3jvwBJ56YWnY/OM+waRrus5f5s8bLlEkk="
        public: "VG+MqMMkpc0yb0//A/mDx6F731TLUCGC7vWPhS0lKHA="
      - private: "aDarXiD7A3p5DCCUxiRuu7mamAX7lqiv41JY6I/HdUg="
        public: "e5gYDuuPSGs2hwBwdwVsCklZ+0v+ItMJ+xNE5UPV2RQ="
    - - private: "WOnEOayVPw+HYh/eLyqr01qpGAiMVy3166iBysUMDU8="
        public: "7ITgF9s9A7QczQt1wkwhWKOuXyYyorxIwhqLm+IiWBE="
      - private: "gGUH5qQMtdFN2HAlG0B1IpyZvkpYCBrZLGYVklt+/Gs="
        public: "htevsdLTXSQmswjnQZtSAr5aWkQpV2a20GE9JkUIwRs="
      - private: "IDHWVAXWqak/Ue/m6UiC8GQ9aBAVmKdZj78xBe3KwWY="
        public: "7i4KlRQQTueh32IMVTEVYWRcQn4IHO2RESb3NvAFCys="
      - private: "wGjp34GJyryw9IX4cTzUOzlVR9Jpz0qs1zNWYSP0yXE="
        public: "CC2O/5PxXTF/BaPTW7J82OMCRZS+cI2hpZ9ldMVgxDQ="
      - private: "2PG6Bgn9vz+nHIvNXjwW20efHHtK9KbVnxKLNtI+h3o="
        public: "r385gOCXxdbIWTUPQBNq8HDarZSd4LizufC9NZb9+Hk="
      - private: "6DOZMqucNHJ9kVRSIXc5zgKcvMck5UxGmFCangTeFXA="
        public: "KKwx4rOwMtJcfRiNOqMCcczZ3tcrEIYd5fuMixwylEM="
      - private: "EAki1orZKPnuv19TtvH8lDpHk6pXf8iD5ZHo60V9hUA="
        public: "1gbpcQytss95gXAkZIxTdzc2GYpsjx9BwJypwYk0jEE="
      - private: "8GNwYMpErDBQ+OIR0ov9JCXp6AqATDBnLL+7jI2W/Xc="
        public: "R9bsfeqUpxkdrLLC6rSlhdkRev/8hnhZuU5jcfMpxFo="
      - private: "MKy+qlA6Jh6vyUbBuenOrWiI7JSgIjjtPP//r/yzfks="
        public: "SNL+zbmCnUmcBI+7s+hd3AdyDhveALvRV1jTG+ke/Ek="
      - private: "wHH4+fZ9h1uJi99gp25nTR5ydyrz4K/8D4FI6eEqPWg="
        public: "uWjBf4jPvsrg7smNQjAv1hAmOrm+2revb9+AsnVnQ1U="
      - private: "2HJrt/fAiKo16F4w4nQe3Ohf8WHR27YEtXBu6oWVylE="
        public: "2atl64Igpb56LycfZKIGJ8FE4bs408Ro6/8DDz5rkhc="
      - private: "iJvqbI5/xTxx+NYNpSQMIm8tH0DScfM43Qp2dbD3kGs="
        public: "7l1ncNcQpf2zCuCtV36Lxq9J/oWyRJhNdSi+qTA4jg4="
    - - private: "kFrk5qM/sEhXABK6OLaTZS2/+AfKVWFIJBuxQIgUlEI="
        public: "cNSWsaV7OVbGCfAsc0Pxgm4ZaDOf5MsE0RXbvelCICQ="
      - private: "6BE9awUzkRpHausLwn2kovDfbtZj6GhkpAePaHQlRG0="
        public: "3Q1BprdnJiMZ6MSVjObnAq4byIMZZzZiai5eljtLqzQ="
      - private: "+MdV0Jk6MCoGS4b13YrWHrBmflan0agGs0CeRCAtZHw="
        public: "kzVQX/56iuQLIpvXVxzGu+SbjUgL5n7+J6E7WikrXEM="
      - private: "aNB2/8UfLlrCcmeHBiwEjxJZSiaUXeWHcCw4duOMLHA="
        public: "fSjNDjiytr6cQVG19vOQcH4PaRHBhUSc/oeZiy01HzU="
      - private: "0AFXtrGMkBm9BFkajZZfFmE8jl86/ilOdlxCRsU49ng="
        public: "EvoM/FquwY1xO0WCF3RwHEHg1jKuYdoZigztkM+2wRo="
      - private: "0B4dAfDcijdGf4EGle5qO4oRCJf5ZHDrqSSzhbM2o2s="
        public: "iEFZZr4345unmF+3bIy/OWivhnsxB9qiMG+BU1WHAxY="
      - private: "8KYQgsn+wmCnl5r36EHBmCeyOoMhvyeWh6G1zsio+Fw="
        public: "qpBOM6lUbn+rO5O9NwJ9WOdvN7TTV95rINAi6Lx/mGU="
      - private: "+P+7FjfXjVGBDeOx94iWy+AxmHFSEuzMXxSEf7syxEc="
        public: "HNEoMvPicQ1MZJCLt58Ub50zkPljK1G6DyNLnAhwHhg="
      - private: "+MgpCjnzcehDZ1iGFd6fPuN8f8ALJpaExVXy+2ybF0g="
        public: "yMevDT4PhnTkhCRWX78kgidduMTNB/R06w9afHjb5S8="
      - private: "YLrzSgReVVKvjSrQWOPPSkl3qICIlon7CiYmLbhwNXs="
        public: "meiTuunJ0qNOsiKdKShVns2qK6m/6uw5OBBRyM4a/Ug="
      - private: "ICkD+v5PyWvMeiMNR8HAmC2PePH5kt1aWS+vy+X533s="
        public: "z/VWTtyUsl5C6gol4chdGXys2dVUmegOXFaFPR37bWI="
      - private: "6HdoLOELntB8u9TL75TiF51dVj+pZWzvhgWnmgZ763k="
        public: "Pk2hu6pLZZfJ+qV3FoFRHAX4sFDbKSZx7K1gFSSR13g="
